version: "3.3"  
services:
  blackshop-mysql:
    container_name: mysql
    image: mysql:8.0.18
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${GLOBAL_TIME_ZONE}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - bs-backend
  blackshop-redis:
     container_name: blackshop-redis
     image: redis
     restart: always
     privileged: true
     environment:
       REDIS_PASS_FILE: /run/secrets/redis-password
       TZ: ${GLOBAL_TIME_ZONE}
     command: [
       "bash", "-c",
       '
        docker-entrypoint.sh
        --requirepass "$$(cat $$REDIS_PASS_FILE)"
       '
     ]
     volumes:
       - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf 
       - ./etc/redis/redis-password:/run/secrets/redis-password
     ports:
       - "${REDIS_PORT}:6379" 
     networks:
      - bs-backend
networks:
  bs-backend:  
    driver: bridge
